$login = Invoke-RestMethod `
  -Method Post `
  -Uri http://localhost:8080/auth/login `
  -ContentType 'application/json' `
  -Body (@{
    username = '<your-username>'
    password = '<your-password>'
  } | ConvertTo-Json)

Invoke-RestMethod `
  -Method Get `
  -Uri http://localhost:8080/projects `
  -Headers @{ Authorization = "Bearer $($login.accessToken)" }